# Generated by Django 5.2 on 2025-05-18 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.cat', verbose_name='Кот-курьер'),
        ),
    ]
