# Generated by Django 5.2.1 on 2025-05-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_order_cat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cat",
            old_name="photo",
            new_name="image",
        ),
    ]
